name: Build C++ Executable with Bash and YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Compile Arcieus.cpp using MSVC with Bash
    - name: Compile with MSVC
      shell: bash
      run: |
        echo "Setting up MSVC environment..."
        mkdir -p output
        echo "Compiling Arcieus.cpp..."
        cl /EHsc Arcieus.cpp /Fe:output/Arcieus.exe || exit 1

    # Step 3: Copy Dependencies with Bash
    - name: Copy Dependencies
      shell: bash
      run: |
        echo "Copying dependencies to output directory..."
        cp icudtl.dat output/ || exit 1
        cp icudtl.dll output/ || exit 1
        cp en-US.pak output/ || exit 1
        cp es.pak output/ || exit 1
        cp uk.pak output/ || exit 1

    # Step 4: Upload Artifacts (Executable and Dependencies)
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Arcieus-and-Dependencies
        path: output/
