name: Build C++ Executable with Dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2019buildtools --params "'--add Microsoft.VisualStudio.Workload.VCTools'" -y

    - name: Initialize Visual Studio Environment
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"
        echo %PATH%

    - name: Verify cl Command
      shell: cmd
      run: cl /?

    - name: Compile Arcieus.cpp with MSVC
      shell: cmd
      run: |
        mkdir output
        cl /EHsc Arcieus.cpp /Fe:output/Arcieus.exe

    - name: Copy Dependencies
      run: |
        xcopy locales output\locales /E /I
        xcopy icudtl.dat output\

    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Arcieus
        path: output/
