name: Build C++ Executable with MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up MSVC
    - name: Setup MSVC
      shell: cmd
      run: |
        echo Setting up MSVC environment...
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"

    # Step 3: Compile the Code
    - name: Compile Arcieus.cpp
      shell: cmd
      run: |
        mkdir output
        cl /EHsc Arcieus.cpp /Fe:output\Arcieus.exe

    # Step 4: Copy Dependencies
    - name: Copy Dependencies
      shell: cmd
      run: |
        copy icudtl.dat output\
        copy icudtl.dll output\
        copy en-US.pak output\
        copy es.pak output\
        copy uk.pak output\

    # Step 5: Upload Artifacts
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Arcieus-and-Dependencies
        path: output/
