name: Build C++ Executable with Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Compile Arcieus.cpp with MSVC
    - name: Compile with MSVC
      shell: cmd
      run: |
        echo Compiling Arcieus.cpp...
        mkdir output
        cl /EHsc Arcieus.cpp /Fe:output\Arcieus.exe

    # Step 3: Copy Dependencies
    - name: Copy Dependencies
      shell: cmd
      run: |
        echo Copying dependencies...
        copy icudtl.dat output\
        copy icudtl.dll output\
        copy en-US.pak output\
        copy es.pak output\
        copy uk.pak output\

    # Step 4: Upload Compiled Artifacts
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Arcieus-and-Dependencies
        path: output/
