name: Build C++ Executable with Bash Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Setup MSVC environment and Compile
    - name: Compile with MSVC using Bash
      shell: bash
      run: |
        echo "Initializing MSVC environment..."
        "/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools/VsDevCmd.bat"
        echo "Creating output directory..."
        mkdir output
        echo "Compiling Arcieus.cpp..."
        cl /EHsc Arcieus.cpp /Fe:output/Arcieus.exe

    # Step 3: Copy Dependencies using Bash
    - name: Copy Dependencies
      shell: bash
      run: |
        echo "Copying dependencies to output directory..."
        cp icudtl.dat output/
        cp icudtl.dll output/
        cp en-US.pak output/
        cp es.pak output/
        cp uk.pak output/

    # Step 4: Upload artifacts
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Arcieus-and-Dependencies
        path: output/
