name: Build C++ Executable with Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Visual Studio Build Tools
    - name: Install Visual Studio Build Tools
      run: |
        echo Installing Visual Studio Build Tools...
        choco install visualstudio2019buildtools --include-optional -y

    # Step 3: Initialize Visual Studio Environment
    - name: Initialize Visual Studio Environment
      shell: cmd
      run: |
        echo Initializing Visual Studio Build Tools...
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" || exit /b 1
        echo Visual Studio Build Tools initialized successfully.

    # Step 4: Compile the Code
    - name: Compile Arcieus.cpp with MSVC
      shell: cmd
      run: |
        mkdir output
        cl /EHsc Arcieus.cpp /Fe:output\Arcieus.exe || exit /b 1
        echo Compilation successful!

    # Step 5: Copy Dependencies
    - name: Copy Dependencies
      shell: cmd
      run: |
        copy icudtl.dat output\ || exit /b 1
        copy icudtl.dll output\ || exit /b 1
        copy en-US.pak output\ || exit /b 1
        copy es.pak output\ || exit /b 1
        copy uk.pak output\ || exit /b 1
        echo Dependencies copied successfully!

    # Step 6: Upload Compiled Artifacts
    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Arcieus-and-Dependencies
        path: output/
